apiVersion: v2
dependencies:
- condition: argus.enabled
  name: argus
  repository: https://logicmonitor.github.io/helm-charts
  tags:
  - logicmonitor
  - argus
  - monitoring
  version: 13.2.0
- condition: collectorset-controller.enabled
  name: collectorset-controller
  repository: https://logicmonitor.github.io/helm-charts
  tags:
  - logicmonitor
  - collectorset-controller
  - monitoring
  version: 11.2.0
- condition: lm-logs.enabled
  name: lm-logs
  repository: https://logicmonitor.github.io/helm-charts
  tags:
  - logicmonitor
  - lm-logs
  - monitoring
  - pod-logs-collection
  - k8s-events-collection
  version: 0.7.0
- condition: lmotel.enabled
  name: lmotel
  repository: https://logicmonitor.github.io/helm-charts
  tags:
  - logicmonitor
  - lmotel
  - monitoring
  version: 1.9.0
- condition: kube-state-metrics.enabled
  name: kube-state-metrics
  repository: https://prometheus-community.github.io/helm-charts
  version: 5.36.0
- name: lmutil
  repository: https://logicmonitor.github.io/helm-charts
  version: 0.1.9
description: A Helm chart for Logicmonitor's Kubernetes monitoring solutions
icon: https://logicmonitor.github.io/helm-charts/lm_logo.png
kubeVersion: '>= 1.16.0-0'
maintainers:
- email: argus@logicmonitor.com
  name: LogicMonitor
name: lm-container
type: application
version: 11.2.0
